### -------------------------------------------------- ###
#   Secrets                                              #
### -------------------------------------------------- ###

# Datadog API Key
---
apiVersion: v1
kind: Secret
metadata:
  name: datadog-api-key
  namespace: vulcan-application
type: generic
stringData:
  api-key: <dd-api-key>


# Vulcan Secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: vulcan-secrets
  namespace: vulcan-application
type: generic
stringData:
  OPENAI_API_KEY: <openai-api-key>
  PASSWORD_PEPPER: <password-pepper>
  SESSION_KEY: <session-key>