targetSystem: "linux"
commonLabels:
  tags.datadoghq.com/env: dev
datadog:
  kubelet:
    tlsVerify: false

  tags:
    - env:dev

  kubeStateMetricsEnabled: false
  kubeStateMetricsCore:
    enabled: true

  namespaceLabelsAsTags:
    team: team
    tags.datadoghq.com/env: env
  nodeLabelsAsTags:
    team: team
    tags.datadoghq.com/env: env
  podLabelsAsTags:
    team: team
    tags.datadoghq.com/env: env

  orchestratorExplorer:
    enabled: true

  apiKeyExistingSecret: "datadog-api-key"
  appKeyExistingSecret: "datadog-app-key"

  clusterName: pupmac-cluster

  networkMonitoring:
    enabled: true

  logs:
    enabled: true
    autoMultiLineDetection: true

  apm:
    portEnabled: false
    socketEnabled: true

  serviceMonitoring:
    enabled: true

  processAgent:
    enabled: true
    processCollection: true

  clusterChecks:
    enabled: true

  ignoreAutoConfig:
    - etcd
    - kube_controller_manager
    - kube_scheduler

  containerExclude: "kube_namespace:kube-system"

  env:
    - name: DD_APM_FEATURES
      value: 'enable_cid_stats'

clusterAgent:
  enabled: true
  admissionController:
    enabled: false

agents:
  image:
    tagSuffix: jmx
  annotations:
    ad.datadoghq.com/agent.logs: '[{"source":"datadog-agent","service":"datadog-agent"}]'
  podSecurity:
    apparmor:
      enabled: true
  volumes:
    - name: logs
      hostPath:
        path: /vulcan-data/logs/
  volumeMounts:
    - name: logs
      mountPath: /vulcan-data/logs/
      readOnly: true