targetSystem: "linux"
commonLabels:
  tags.datadoghq.com/env: dev
datadog:
  kubelet:
    tlsVerify: false

  kubeStateMetricsEnabled: false
  kubeStateMetricsCore:
    enabled: true

  namespaceLabelsAsTags:
    team: team
    tags.datadoghq.com/env: env
  nodeLabelsAsTags:
    team: team
    tags.datadoghq.com/env: env
  podLabelsAsTags:
    team: team
    tags.datadoghq.com/env: env

  orchestratorExplorer:
    enabled: true

  apiKey: <dd-api-key>
  appKey: <dd-app-key>
  clusterName: pupmac-cluster

  networkMonitoring:
    enabled: true

  logs:
    enabled: true

  apm:
    portEnabled: false
    socketEnabled: true

  serviceMonitoring:
    enabled: false

  processAgent:
    enabled: false
    processCollection: false

  clusterChecks:
    enabled: true

  ignoreAutoConfig:
    - etcd
    - kube_controller_manager
    - kube_scheduler

  containerExclude: "kube_namespace:kube_system"

clusterAgent:
  enabled: true
  admissionController:
    enabled: false

agents:
  annotations:
    ad.datadoghq.com/agent.logs: '[{"source":"datadog-agent","service":"datadog-agent"}]'
  volumes:
    - name: logs
      persistentVolumeClaim:
        claimName: vulcan-logs-pvc
  volumeMounts:
    - name: logs
      mountPath: /vulcan-data/logs/
      readOnly: true