name: "CI/CD Pipeline"
run-name: "CI/CD deployment of ${{ github.ref }} by @${{ github.actor }}"
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-authenticator:
    name: "Test Authenticator"
    runs-on: pupmac-runner
    container: python:3.12
    steps:
    - name: "Checkout Repo"
      uses: actions/checkout@v6
      with:
        sparse-checkout: |
          services/authenticator
    - name: "Set Environment Variables"
      run: |
        echo "DD_ENV=cicd" >> $GITHUB_ENV
        echo "DD_SERVICE=authenticator" >> $GITHUB_ENV
        echo "DD_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "CERT_FOLDER=$(pwd)/services/authenticator/certificate" >> $GITHUB_ENV
        echo "PW_PEPPER=${{ secrets.VULCAN_PASSWORD_PEPPER }}" >> $GITHUB_ENV
    - name: "Install DDTrace"
      run: pip3 install ddtrace --quiet --root-user-action=ignore --upgrade
    - name: "Install Dependencies"
      run: pip3 install -r services/authenticator/requirements.txt --quiet --root-user-action=ignore --upgrade 
    - name: "Run Authenticator"
      run: |
        ddtrace-run python3 services/authenticator/authenticator/main.py &
        for i in {1..12}; do
          if curl --fail --silent --insecure https://localhost/health; then
            echo "Health check succeeded";
            exit 0;
          fi
          echo "Waiting for health endpoint... ($i)";
          sleep 5;
        done
        echo "Health check failed after retries";
        exit 1

  build-delphi:
    name: "Test Delphi"
    runs-on: pupmac-runner
    container: python:3.12
    steps:
    - name: "Checkout Repo"
      uses: actions/checkout@v6
      with:
        sparse-checkout: |
          services/delphi
    - name: "Set Environment Variables"
      run: |
        echo "DD_ENV=cicd" >> $GITHUB_ENV
        echo "DD_SERVICE=delphi" >> $GITHUB_ENV
        echo "DD_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "CERT_FOLDER=$(pwd)/services/delphi/certificate" >> $GITHUB_ENV
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
        echo "DD_API_KEY=${{ secrets.DD_API_KEY }}" >> $GITHUB_ENV
    - name: "Install Datadog Tracer"
      run: pip3 install ddtrace --quiet --root-user-action=ignore --upgrade
    - name: "Install Dependencies"
      run: |
        pip3 uninstall kafka --quiet --root-user-action=ignore
        pip3 uninstall kafka-python --quiet --root-user-action=ignore
        pip3 install -r services/delphi/requirements.txt --quiet --root-user-action=ignore --upgrade 
    - name: "Run Delphi"
      run: |
        ddtrace-run python3 services/delphi/delphi/main.py &
        for i in {1..12}; do
          if curl --fail --silent --insecure https://localhost/health; then
            echo "Health check succeeded";
            exit 0;
          fi
          echo "Waiting for health endpoint... ($i)";
          sleep 5;
        done
        echo "Health check failed after retries";
        exit 1

  build-god-manager:
    name: "Test God-Manager"
    runs-on: pupmac-runner
    container: golang:1.25
    steps:
    - name: "Checkout Repo"
      uses: actions/checkout@v6
      with:
        sparse-checkout: |
          services/god-manager
    - name: "Set Environment Variables"
      run: |
        echo "DD_ENV=cicd" >> $GITHUB_ENV
        echo "DD_SERVICE=god-manager" >> $GITHUB_ENV
        echo "DD_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "CERT_FOLDER=$(pwd)/services/god-manager/certificate" >> $GITHUB_ENV
    - name: "Install Dependencies"
      run: |
        cd services/god-manager
        go mod download && go mod verify
    - name: "Install Orchestrion"
      run: |
        cd services/god-manager
        GOPROXY=direct go install github.com/DataDog/orchestrion@latest
    - name: "Build Binary"
      run: |
        cd services/god-manager
        orchestrion go build -o build/god-manager -tags appsec god-manager/...
    - name: "Run God-Manager"
      run: |
        build/god-manager &
        for i in {1..12}; do
          if curl --fail --silent --insecure https://localhost/health; then
            echo "Health check succeeded";
            exit 0;
          fi
          echo "Waiting for health endpoint... ($i)";
          sleep 5;
        done
        echo "Health check failed after retries";
        exit 1

  build-scribe:
    name: "Test Scribe"
    runs-on: pupmac-runner
    container: node:18
    steps:
    - name: "Checkout Repo"
      uses: actions/checkout@v6
      with:
        sparse-checkout: |
          services/scribe
    - name: "Set Environment Variables"
      run: |
        echo "DD_ENV=cicd" >> $GITHUB_ENV
        echo "DD_SERVICE=scribe" >> $GITHUB_ENV
        echo "DD_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "CERT_FOLDER=$(pwd)/services/scribe/certificate" >> $GITHUB_ENV
    - name: "Install Dependencies"
      run: |
        cd services/scribe
        npm install .
    - name: "Run Scribe"
      run: |
        cd services/scribe
        npm start &
        for i in {1..12}; do
          if curl --fail --silent --insecure https://localhost/health; then
            echo "Health check succeeded";
            exit 0;
          fi
          echo "Waiting for health endpoint... ($i)";
          sleep 5;
        done
        echo "Health check failed after retries";
        exit 1

  build-user-manager:
    name: "Test User-Manager"
    runs-on: pupmac-runner
    container: node:18
    steps:
    - name: "Checkout Repo"
      uses: actions/checkout@v6
      with:
        sparse-checkout: |
          services/user-manager
    - name: "Set Environment Variables"
      run: |
        echo "DD_ENV=cicd" >> $GITHUB_ENV
        echo "DD_SERVICE=user-manager" >> $GITHUB_ENV
        echo "DD_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "CERT_FOLDER=$(pwd)/services/user-manager/certificate" >> $GITHUB_ENV
    - name: "Install Dependencies"
      run: |
        cd services/user-manager
        npm install .
    - name: "Run User Manager"
      run: |
        cd services/user-manager
        npm start &
        for i in {1..12}; do
          if curl --fail --silent --insecure https://localhost/health; then
            echo "Health check succeeded";
            exit 0;
          fi
          echo "Waiting for health endpoint... ($i)";
          sleep 5;
        done
        echo "Health check failed after retries";
        exit 1

  build-vulcan:
    name: "Test Vulcan"
    runs-on: pupmac-runner
    container: maven:3.9-eclipse-temurin-21
    steps:
    - name: "Checkout Repo"
      uses: actions/checkout@v6
      with:
        sparse-checkout: |
          services/vulcan
    - name: "Set Environment Variables"
      run: |
        echo "DD_ENV=cicd" >> $GITHUB_ENV
        echo "DD_SERVICE=vulcan" >> $GITHUB_ENV
        echo "DD_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "CERT_FOLDER=$(pwd)/services/vulcan/certificate" >> $GITHUB_ENV
        echo "FRONTEND_VERSION=fe-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "VLCN_SESSION_KEY=${{ secrets.VULCAN_SESSION_KEY }}" >> $GITHUB_ENV
        echo "PW_PEPPER=${{ secrets.VULCAN_PASSWORD_PEPPER }}" >> $GITHUB_ENV
    - name: "Install Datadog Tracer"
      run: curl -fLSS -o dd-java-agent.jar https://dtdg.co/latest-java-tracer
    - name: "Install Dependencies"
      run: mvn install -q -f services/vulcan/pom.xml
    - name: "Configure Certificates"
      run: |
        keytool -import -noprompt -alias user-manager-cert -cacerts -file services/user-manager/certificate/cert.pem -storepass changeit
        keytool -import -noprompt -alias god-manager-cert -cacerts -file services/god-manager/certificate/cert.pem -storepass changeit
        keytool -import -noprompt -alias authenticator-cert -cacerts -file services/authenticator/certificate/cert.pem -storepass changeit
        keytool -import -noprompt -alias delphi-cert -cacerts -file services/delphi/certificate/cert.pem -storepass changeit
        cp /opt/java/openjdk/lib/security/cacerts services/vulcan/cacert
    - name: "Run Vulcan"
      run: |
        java -javaagent:dd-java-agent.jar \
          -Djavax.net.ssl.trustStore=services/vulcan/cacert \
          -Dlog4j2.configurationFile=services/vulcan/src/log4j2.xml \
          -Dvulcan.session.key={{ secret.VULCAN_SESSION_KEY }} \
          -jar services/vulcan/target/vulcan.jar \
          --logging.config=services/vulcan/src/log4j2.xml &
        for i in {1..12}; do
          if curl --fail --silent --insecure https://localhost/health; then
            echo "Health check succeeded";
            exit 0;
          fi
          echo "Waiting for health endpoint... ($i)";
          sleep 5;
        done
        echo "Health check failed after retries";
        exit 1

  deploy:
    name: "Deploy to Cluster"
    runs-on: pupmac-runner
    container: ubuntu:24
    needs: [ build-authenticator, build-delphi, build-god-manager, build-scribe, build-user-manager, build-vulcan ]
    steps:
    - name: "Download kubectl"
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - name: "Validate kubectl"
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
        echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
    - name: "Install kubectl"
      run: |
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    - name: "Configure kubectl"
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
    - name: "Deploy Secrets"
      run: |
        sed -i -e s/<dd-api-key>/${{ secrets.DD_API_KEY }}/g secrets.yaml
        sed -i -e s/<openai-api-key>/${{ secrets.OPENAI_API_KEY }}/g secrets.yaml
        sed -i -e s/<password-pepper>/${{ secrets.VULCAN_PASSWORD_PEPPER }}/g secrets.yaml
        sed -i -e s/<session-key>/${{ secrets.VULCAN_SESSION_KEY }}/g secrets.yaml
        kubectl apply -f secrets.yaml
    - name: "Deploy Application"
      run: |
        kubectl apply -f deployment.yaml

  test:
    name: "End to End Testing"
    runs-on: pupmac-runner
    container: ubuntu:24
    needs: deploy
    steps:
    - name: "Run Synthetic Tests"
      uses: DataDog/synthetics-ci-github-action@v3.8.2
      with:
        api-key: ${{ secrets.DD_API_KEY }}
        app-key: ${{ secrets.DD_APP_KEY }}
        public-ids: |
          abc-d3f-ghi
          jkl-mn0-pqr
    
