name: vulcan-monitoring
services:
  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    container_name: datadog-agent
    cgroup: host
    ports:
      - 8126:8126
      - 8125:8125
    networks:
      pupkube:
        ipv4_address: 192.168.49.252
    environment:
      - DD_API_KEY=<dd-api-key>
      - DD_APP_KEY=<dd-app-key>
      - DD_ENV=dev
      - DD_CONTAINER_EXCLUDE=name:minikube
      - DD_HOSTNAME=pupmac
      - DD_DOGSTATSD_SOCKET=/var/run/datadog/dsd.socket
      - DD_APM_RECEIVER_SOCKET=/var/run/datadog/apm.socket
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_APM_IGNORE_RESOURCES="^ismaster admin\.\$cmd$","^hello admin\.\$cmd$","^REDIGO\.CONN\.FLUSH$"
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=false
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_SYSTEM_PROBE_NETWORK_ENABLED=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_INVENTORIES_CONFIGURATION_ENABLED=true
      - HOST_ROOT='/host/root'
    volumes:
      - /var/run/datadog:/var/run/datadog
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /etc/passwd:/etc/passwd:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run
      - /Users/matthew.brazill/vulcan-data:/vulcan-data
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /sys/kernel/debug:/sys/kernel/debug
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
      - /var/tmp/datadog-agent/system-probe/build:/var/tmp/datadog-agent/system-probe/build
      - /var/tmp/datadog-agent/system-probe/kernel-headers:/var/tmp/datadog-agent/system-probe/kernel-headers
      - /etc/apt:/host/etc/apt
      - /etc/yum.repos.d:/host/etc/yum.repos.d
      - /etc/zypp:/host/etc/zypp
      - /etc/pki:/host/etc/pki
      - /etc/yum/vars:/host/etc/yum/vars
      - /etc/dnf/vars:/host/etc/dnf/vars
      - /etc/rhsm:/host/etc/rhsm
      - /:/host/root:ro
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
      - SYS_PTRACE
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
      - IPC_LOCK
      - CHOWN
    security_opt:
      - apparmor:unconfined


  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    networks:
      pupkube:
        ipv4_address: 192.168.49.253
    environment:
      - DD_API_KEY=<dd-api-key>
    volumes:
      - ./otel-collector/otel-collector.yaml:/etc/otelcol-contrib/config.yaml


  private-location:
    platform: linux/amd64
    image: gcr.io/datadoghq/synthetics-private-location-worker:latest
    stdin_open: true
    container_name: datadog-private-location
    networks:
      pupkube:
        ipv4_address: 192.168.49.254
    volumes:
      - ./datadog-synthetics/worker-config-docker.json:/etc/datadog/synthetics-check-runner.json
    shm_size: 1gb
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 12G
    healthcheck:
      retries: 1
      test: ["CMD", "wget", "-O", "/dev/null", "-q", "http://localhost:8080/liveness"]
      timeout: 2s
      interval: 10s
      start_period: 30s
networks:
  pupkube:
    name: pupkube
    external: true